"use client";

export { SVGComponentProps } from "./template";
export * from "./icons/alerts";
export * from "./icons/arrow";
export * from "./icons/charts";
export * from "./icons/communication";
export * from "./icons/editor";
export * from "./icons/education";
export * from "./icons/files";
export * from "./icons/finance";
export * from "./icons/general";
export * from "./icons/layout";
export * from "./icons/maps";
export * from "./icons/media-devices";
export * from "./icons/security";
export * from "./icons/shapes";
export * from "./icons/time";
export * from "./icons/users";
export * from "./icons/weather";
export * from "./icons/development";
