"use client";

export { SVGComponentProps } from "./template";
export * as Alerts from "./icons/alerts";
export * as Arrow from "./icons/arrow";
export * as Charts from "./icons/charts";
export * as Communication from "./icons/communication";
export * as Editor from "./icons/editor";
export * as Education from "./icons/education";
export * as Files from "./icons/files";
export * as Finance from "./icons/finance";
export * as General from "./icons/general";
export * as Layout from "./icons/layout";
export * as Maps from "./icons/maps";
export * as MediaDevices from "./icons/media-devices";
export * as Security from "./icons/security";
export * as Shapes from "./icons/shapes";
export * as Time from "./icons/time";
export * as Users from "./icons/users";
export * as Weather from "./icons/weather";
export * as Development from "./icons/development";

export * from "./icons/alerts";
export * from "./icons/arrow";
export * from "./icons/charts";
export * from "./icons/communication";
export * from "./icons/editor";
export * from "./icons/education";
export * from "./icons/files";
export * from "./icons/finance";
export * from "./icons/general";
export * from "./icons/layout";
export * from "./icons/maps";
export * from "./icons/media-devices";
export * from "./icons/security";
export * from "./icons/shapes";
export * from "./icons/time";
export * from "./icons/users";
export * from "./icons/weather";
export * from "./icons/development";
